version: '3.7'

services:
  db:
    container_name: "mysql_database"
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    # setting some env vars to create the DB
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "bni_map_legacy"
      MYSQL_USER: "derpen"
      MYSQL_PASSWORD: "pass"
      # OR if you want to use "root" as the user, just these two lines
      # MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      # MYSQL_DATABASE: ${DATABASE_NAME}

    # we mount a data volume to make sure we don't lose data
    volumes:
      - ./mysql_data:/var/lib/mysql
  api:
    container_name:  "bni_map_legacy"
    # we want to use the image which is build from our Dockerfile
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    # we are depending on the mysql backend
    depends_on:
      - db

networks:
  default:
volumes:
  mysql_data:
